version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: user
      DB_PASSWORD: secret
    depends_on:
      - db
    command: flask run --host=0.0.0.0

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  db_data: